### PR TITLE
Adding all building blocks to run dc2hpss.py script

### PR DESCRIPTION
**Pull request by ArturAkh**

### CODE REVIEW

**Comment by XMol** [comment]
If you want to provide your own licence, you are of course allowed to do so. But maybe use the same spelling (license != licence)? 😉

**Comment by ArturAkh** [comment]
As you wish... 180bc07e8c5a651f5f7985a8b659ac851651fa6d

**Comment by hmushegh** [comment]
Hi. 

thanks. I have a few things to mention. 

I offer to add or modify the setup for the ATLAS use-case.
Please upload your own license for the script that you have. This is importantn. 

Cheers,
Haykuhi

**Comment by ArturAkh** [comment]
Hi Haykuhi,

Thanks! Concerning License: This is the one contructed from what you've provided. Just changed the name of it from LICENCE to LICENSE.

On ATLAS specific setup: I can add the ATLAS configuration and file-family calculation into the corresponding files.

**Comment by ArturAkh** [comment]
Should I also add ATLAS specific example for writing? I can extract dCache call examples for a big dataset and for a small dataset

**Comment by hmushegh** [comment]
I think we need to provide them with a working script for the ATLAS use case that is currently in production.

**Comment by ArturAkh** [comment]
Yes, I'll extend the existing configurations in such a way, that it is equivalent to the ATLAS production setup. Doing it in a separate branch, will take just a few moments. We may discuss further there.

**Comment by hmushegh** [comment]
ok, thx

**Comment by ArturAkh** [comment]
Here the new PR: https://github.com/KIT-SCC/dc2hpss/pull/2

**Pull request merged**
